# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-03 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_rec', '0002_auto_20191202_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField()),
            ],
        ),
    ]
